//
//  ProductAdditionState.swift
//  SaleRetail
//
//  Created by D.Ace on 14/11/24.
//

import Foundation
import UIKit

class ProductAdditionState: ObservableObject {
    @Published var products: [ProductModel] = []
    
    init(products: [ProductModel]) {
        self.products = [
            ProductModel(id: 1,
                  group: 1,
                  provider: 1,
                  unit: 1,
                  smallUnit: 1,
                  unitExchangeRate: 1,
                  buyPrice: 1242,
                  sellPrice: 234,
                  smallUnitSellPrice: 1111,
                  weight: 1111,
                  smallUnitWeight: 111,
                  minSellUnit: 111,
                  isDeleted: false,
                  hasExpiredDate: false,
                  groupName: "",
                  providerName: "",
                  unitName: "thùng",
                  smallUnitName: "",
                  minSellUnitName: "",
                  code: "SP0001",
                  name: "Tuong ot ha anh"
                 ),
            ProductModel(id: 1,
                  group: 1,
                  provider: 1,
                  unit: 1,
                  smallUnit: 1,
                  unitExchangeRate: 1,
                  buyPrice: 1242,
                  sellPrice: 234,
                  smallUnitSellPrice: 1111,
                  weight: 1111,
                  smallUnitWeight: 111,
                  minSellUnit: 111,
                  isDeleted: false,
                  hasExpiredDate: false,
                  groupName: "",
                  providerName: "",
                  unitName: "Bịch",
                  smallUnitName: "",
                  minSellUnitName: "",
                  code: "SP0001",
                  name: "Tuong ot ha anh"
                 ),
            ProductModel(id: 1,
                  group: 1,
                  provider: 1,
                  unit: 1,
                  smallUnit: 1,
                  unitExchangeRate: 1,
                  buyPrice: 1242,
                  sellPrice: 234,
                  smallUnitSellPrice: 1111,
                  weight: 1111,
                  smallUnitWeight: 111,
                  minSellUnit: 111,
                  isDeleted: false,
                  hasExpiredDate: false,
                  groupName: "",
                  providerName: "",
                  unitName: "chai",
                  smallUnitName: "",
                  minSellUnitName: "",
                  code: "SP0001",
                  name: "Tuong ot ha anh"
                 ),
            ProductModel(id: 1,
                  group: 1,
                  provider: 1,
                  unit: 1,
                  smallUnit: 1,
                  unitExchangeRate: 1,
                  buyPrice: 1242,
                  sellPrice: 234,
                  smallUnitSellPrice: 1111,
                  weight: 1111,
                  smallUnitWeight: 111,
                  minSellUnit: 111,
                  isDeleted: false,
                  hasExpiredDate: false,
                  groupName: "",
                  providerName: "",
                  unitName: "lọ",
                  smallUnitName: "",
                  minSellUnitName: "",
                  code: "SP0001",
                  name: "Tuong ot ha anh"
                 ),
            ProductModel(id: 1,
                  group: 1,
                  provider: 1,
                  unit: 1,
                  smallUnit: 1,
                  unitExchangeRate: 1,
                  buyPrice: 1242,
                  sellPrice: 234,
                  smallUnitSellPrice: 1111,
                  weight: 1111,
                  smallUnitWeight: 111,
                  minSellUnit: 111,
                  isDeleted: false,
                  hasExpiredDate: false,
                  groupName: "",
                  providerName: "",
                  unitName: "",
                  smallUnitName: "",
                  minSellUnitName: "",
                  code: "SP0001",
                  name: "Tuong ot ha anh"
                 ),
            ProductModel(id: 1,
                  group: 1,
                  provider: 1,
                  unit: 1,
                  smallUnit: 1,
                  unitExchangeRate: 1,
                  buyPrice: 1242,
                  sellPrice: 234,
                  smallUnitSellPrice: 1111,
                  weight: 1111,
                  smallUnitWeight: 111,
                  minSellUnit: 111,
                  isDeleted: false,
                  hasExpiredDate: false,
                  groupName: "",
                  providerName: "",
                  unitName: "",
                  smallUnitName: "",
                  minSellUnitName: "",
                  code: "SP0001",
                  name: "Tuong ot ha anh"
                 ),
            ProductModel(id: 1,
                  group: 1,
                  provider: 1,
                  unit: 1,
                  smallUnit: 1,
                  unitExchangeRate: 1,
                  buyPrice: 1242,
                  sellPrice: 234,
                  smallUnitSellPrice: 1111,
                  weight: 1111,
                  smallUnitWeight: 111,
                  minSellUnit: 111,
                  isDeleted: false,
                  hasExpiredDate: false,
                  groupName: "",
                  providerName: "",
                  unitName: "",
                  smallUnitName: "",
                  minSellUnitName: "",
                  code: "SP0001",
                  name: "Tuong ot ha anh"
                 )
        ]
    }
    
    
}
